name: example
description: Gernerate model class from Json files.
version: 0.0.1
author: windego <zhangwj0520@hotmail.com>
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  json_model:
    path: ../
