name: json_model
description: Gernerating Dart model class from Json file.
version: 0.0.1
author: zhangweijie
homepage: https://github.com/windego/json_model.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  args: ^1.5.2
  build: ^1.2.2
  glob: ^1.2.0
  logging: ^0.11.4
  io: ^0.3.3
  build_resolvers: ^1.3.3
  build_runner_core: ^4.4.0
  build_runner: ^1.7.4
  json_annotation: ^3.0.1
  json_serializable: ^3.2.5
  path: ^1.6.4
dev_dependencies:
  test: ^1.5.1
